name: Monthly Cookie Scan

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install puppeteer node-fetch

      - name: Install Chrome for Puppeteer
        run: npx puppeteer browsers install chrome

      - name: Run cookie scanner
        run: node cookie-scan.js
